version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - finance-network

  backend:
    container_name: backend
    image: backend:1.0.0
    build:
      context: ./api
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      DB_HOST: 172.31.0.3
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: finance
    networks:
      - finance-network
    depends_on:
      - postgres
    links:
      - postgres:postgres

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./web
    ports:
      - "4200:80"
    networks:
      - finance-network
    depends_on:
      - backend

networks:
  finance-network:
    name: finance-network
    driver: bridge
