version: '3.7'

services:
  backend:
    container_name: backend
    image: backend:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
